Offer possibility to clean up semantics
pulyaevskiy/quill-delta-dart pull request #25
Opened 2021-08-08 07:06 UTC by amantoux

By default `diff match patch` produces this optimum diff.
Offer the option to compute a human readable diff

2021-08-08 07:06 UTC, amantoux commented
@pulyaevskiy can you please review?
Cheers

2021-08-12 03:55 UTC, pulyaevskiy requested changes
Thanks, this looks good overall. Just needs some docs I think.

2021-08-12 03:55 UTC, pulyaevskiy commented on lib/quill_delta.dart
> +  Delta diff(Delta other, {bool cleanupSemantic = true}) {
Could you add some docs regarding `cleanupSemantic`? It's not clear for me what semantic means in this context...

2021-08-12 06:48 UTC, amantoux commented on lib/quill_delta.dart
> +  Delta diff(Delta other, {bool cleanupSemantic = true}) {
Done, sorry about that

2021-08-13 03:47 UTC, pulyaevskiy approved these changes
LGTM, thanks for adding the docs!

2021-08-13 03:48 UTC, merged

2021-08-13 03:54 UTC, pulyaevskiy commented
Published as `3.0.0-nullsafety.2`.